// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGPXjVq2HnORAEIlWd8cIkvbxWVsw15O4',
    appId: '1:776882616672:web:101f9508942e9783404605',
    messagingSenderId: '776882616672',
    projectId: 'leadme-matsuda',
    authDomain: 'leadme-matsuda.firebaseapp.com',
    storageBucket: 'leadme-matsuda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY4U2xyADUAUv7wHenaEA8riZOVUkVoWM',
    appId: '1:776882616672:android:9c2f0dac4772ef44404605',
    messagingSenderId: '776882616672',
    projectId: 'leadme-matsuda',
    storageBucket: 'leadme-matsuda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdVTT67J_TTwFflGirYni6JyYk9YZk-zU',
    appId: '1:776882616672:ios:96e206cb6101b7d8404605',
    messagingSenderId: '776882616672',
    projectId: 'leadme-matsuda',
    storageBucket: 'leadme-matsuda.firebasestorage.app',
    iosClientId: '776882616672-7kgii0suk3q0gj2787buae2dems0o93g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdVTT67J_TTwFflGirYni6JyYk9YZk-zU',
    appId: '1:776882616672:ios:96e206cb6101b7d8404605',
    messagingSenderId: '776882616672',
    projectId: 'leadme-matsuda',
    storageBucket: 'leadme-matsuda.firebasestorage.app',
    iosClientId: '776882616672-7kgii0suk3q0gj2787buae2dems0o93g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorial1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGPXjVq2HnORAEIlWd8cIkvbxWVsw15O4',
    appId: '1:776882616672:web:fd5bd64e97ae5e12404605',
    messagingSenderId: '776882616672',
    projectId: 'leadme-matsuda',
    authDomain: 'leadme-matsuda.firebaseapp.com',
    storageBucket: 'leadme-matsuda.firebasestorage.app',
  );

}